#!/usr/bin/env python3
"""Module for calculating polynomial integrals."""


def poly_integral(poly, C=0):
    """Calculates the integral of a polynomial.

    Args:
        poly (list): list of coefficients
        C (int): constant of integration

    Returns:
        list: new list of coefficients of the integral
        None: if poly or C is invalid
    """
    if not isinstance(poly, list) or len(poly) == 0:
        return None

    if not all(isinstance(x, (int, float)) for x in poly):
        return None

    if not isinstance(C, int):
        return None

    result = [C]

    for i in range(len(poly)):
        coef = poly[i] / (i + 1)

        # əgər float amma əslində integerdirsə → int et
        if coef == int(coef):
            coef = int(coef)

        result.append(coef)

    return result
